### ISSUE TITLE
Issue from tutoring 

### ISSUE THREAD

**Issue by madelyng8** [madelyng8/responsive-typography#1]
@MackenzieRose

**Comment by MacKenzieRose** [comment]
Hey Matti,

So to start with, Markbot's compiling errors from having empty selectors in your css file (ex. article p on line 39), so watch out for those.

Next, for your article, you'll find that if you set your margin values to "0 auto" (such that the top and bottom margins are zero, and the left and right will be automatically determined) your text will always sit in the center of your browser window, regardless of the width. I also found that putting padding values of "0.05em 1em 0" for your article will get your header text perfectly aligned. (A bit of a brute force solution, but you get the idea)

Start with those changes, and you should be able to get the rest of your text to align with some other minor styling changes in your css. Tag me again if you need help! :)

**Comment by MacKenzieRose** [comment]
If this issue has been resolved, feel free to close it :)

Cheers!
MacKenzie

**Comment by MacKenzieRose** [comment]
If this issue has been addressed, please make sure to close it 😄
