### ISSUE TITLE
Issue from tutoring - two screenshots both 1% difference (november 22)

### ISSUE THREAD

**Issue by madelyng8** [madelyng8/responsive-typography#2]
@MackenzieRose

**Comment by MacKenzieRose** [comment]
Hey @madelyng8!

Can you make sure all of your code is committed? The screenshots I have when I load this are about 20% or more.

**Comment by madelyng8** [comment]
Yes, Just did

**Comment by MacKenzieRose** [comment]
Hey @madelyng8!

Looking pretty close!

To get things within Markbot's parameters, let's make some changes in the respective media query sizes.

For the 38 screen width (608 px), let's adjust your article padding so it's a little smaller (.7rem). Your h1 padding also isn't doing anything, so let's delete that selector, just to clean up your code a little bit. Finally, if we adjust the padding-left value you have on your general paragraph selector, down to .3rem, we see the paragraph text align itself.

For the larger screenshot, if you reduce the padding in the html selector (I've got somewhere around 3.1 rem) it seems to pass Markbot.


Let me know how that goes.

**Comment by MacKenzieRose** [comment]
If this issue has been resolved, feel free to close it :)

Cheers!
MacKenzie

**Comment by MacKenzieRose** [comment]
If this issue has been addressed, please make sure to close it 😄
